### ISSUE TITLE
How to auto-import from component library in node_modules?

### ISSUE THREAD

**Issue by bwklein** [yuanchuan/vite-plugin-autoimport#12]
What's the best way to use components that I have installed into the project through NPM package.json?

**Comment by yuanchuan** [comment]
Use `module` or `mapping`:

```js
autoImport({
  components: [],

  mapping: {
    SomeLib: `import SomeLib from 'some-lib'`
  }
})
```

**Comment by bwklein** [comment]
Do you have an example or docs for these features?  I'm not sure how I would use that in my case.

**Comment by bwklein** [comment]
For example, I have a `<Video v="XXXXXX"/>` component in my markdown.  It comes from `import {Video} from tecitheme/components/Video.svelte'`

If I add that import line to the script in markdown the component works as expected.

**Comment by yuanchuan** [comment]
Yeah there are examples at the bottom of readme file. 

```js
autoImport({
  /* .. */
  mapping: {
    Video: `import {Video} from 'tecitheme/components/Video.svelte'`
  }
})
```

**Comment by yuanchuan** [comment]
It means how/where to import the `Video` component. They can be component, variable, or a function:

```js
autoImport({
  /* .. */
  mapping: {

    VideoX: `import { Video as VideoX } from 'tecitheme/components/Video.svelte'`,

    T: `import T from './lib/language/get-text.js'`,
   
    /* I wouldn't suggest this */
    GLOBAL_VAR: `const GLOBAL_VAR = 'hello world';`,
  }
})

```

**Comment by bwklein** [comment]
Ok, instead of mapping all of the components individually, would it be possible to add the node module to the "components" array and have them all imported automatically?  That's how it works if they are in a local folder, like `./src/lib/components`.

**Comment by yuanchuan** [comment]
I suggest import them manually and explicitly for the third-party components. There's also a `module` option for selecting multiple items for a module.

```js
autoImport({
  /* .. */
  module: {
    'some-component-lib': ['Video', 'Caption']
  }
})
```

Which means:

```js
import { Video, Caption } from 'some-component-lib'
```

**Comment by bwklein** [comment]
Ok this works well for me. Thank you.

**Comment by bwklein** [comment]
> ```js
> autoImport({
>   /* .. */
>   module: {
>     'some-component-lib': ['Video', 'Caption']
>   }
> })
> ```

How would you do this in my case where the components are in the 'components' subdirectory of the theme?

BTW, the following code works for me now.

```
mapping: {
    Video: `import Video from 'tecitheme/components/Video.svelte'`
  }
```

**Comment by yuanchuan** [comment]
The package `tecitheme` is missing an entry file like `index.js` for exporting all packages outside. So you have to import them one by one
