### ISSUE TITLE
TS let statement breaking import

### ISSUE THREAD

**Issue by stolinski** [yuanchuan/vite-plugin-autoimport#19]
Interesting one here.

### Works

```
<script lang="ts">
	import { fly } from 'svelte/transition'
</script>
```

### Doesn't Work
```
<script lang="ts">
	import { fly } from 'svelte/transition'

	let y: number
</script>
```

Something about this `let y: number` is breaking the import in this file. I don't have a reproduction yet, but I can make one.

**Comment by yuanchuan** [comment]
Somehow the `svelte.preprocess()` doesn't have any effect

https://github.com/yuanchuan/sveltekit-autoimport/blob/main/src/index.js#L110

**Comment by yuanchuan** [comment]
Please try `1.6.7`. I've tested locally and it works now.

**Comment by stolinski** [comment]
Works perfectly. Thank you.
