### ISSUE TITLE
auto import { base } from "$app/paths"?

### ISSUE THREAD

**Issue by yannickrohmer** [yuanchuan/vite-plugin-autoimport#2]
Is there a way to automatically import { base } from "$app/paths"?
I can't figure out.

**Comment by yuanchuan** [comment]
Yes, using `mapping`:

```js
autoImport({
  mapping: {
    base: `import { base } from "$app/paths"`,
  }
})
```

However, the `base` is a very common word, it's also possible to rename it to another word.

```js
autoImport({
  mapping: {
    AppBase: `import { base as AppBase } from "$app/paths"`,
  }
});
```
