### ISSUE TITLE
Error: Failed to parse source for import analysis because the content contains invalid JS syntax.

### ISSUE THREAD

**Issue by hartwm** [yuanchuan/vite-plugin-autoimport#28]
I have a fairly blank starter theme running on sveltekit latest which uses sveltekit plugin for vite and a vite.config file.

my vite.config.js file looks like
```
import { sveltekit } from '@sveltejs/kit/vite'; 
import autoImport from 'sveltekit-autoimport'; 

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [
		sveltekit(), 
                autoImport({
			components: [{ name: 'src/components/skeleton' } ],
		})
	]
};

export default config;
```
the src/components/skeleton has one file at src/components/skeleton/Menu.svelte for testing with this markup
`<h1>This is a menu component</h1>`

error message
```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
    at formatError (/Users/whart/www/koios/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39055:46)
    at TransformContext.error (/Users/whart/www/koios/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39051:19)
    at TransformContext.transform (/Users/whart/www/koios/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58269:22)
    at async TransformContext.plugin.transform (file:///Users/whart/www/koios/node_modules/vite-plugin-inspect/dist/index.mjs:164:25)
    at async Object.transform (/Users/whart/www/koios/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30)
    at async doTransform (/Users/whart/www/koios/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:50012:29)
```

**Comment by yuanchuan** [comment]
Well, this is a headache

**Comment by yuanchuan** [comment]
How about to put `autoimport()` above `sveltekit()` in the `plugins` object?

**Comment by hartwm** [comment]
This works! Thank you

I did notice some type issues with component 
`Argument of type '{ components: string[]; include: string[]; }' is not assignable to parameter of type 'string | string[] | undefined'.
  Object literal may only specify known properties, and 'components' does not exist in type 'string[]'.ts(2345)`

**Comment by yuanchuan** [comment]
> This works! Thank you
> 
> I did notice some type issues with component `Argument of type '{ components: string[]; include: string[]; }' is not assignable to parameter of type 'string | string[] | undefined'. Object literal may only specify known properties, and 'components' does not exist in type 'string[]'.ts(2345)`

Thanks for reporting. It seems the warning was caused by the JSDoc comments﻿. I'll fix that

**Comment by stolinski** [comment]
~~For me moving the Auto Import plugin above SK gives Component is not defined errors for auto imported ones and invalid syntax errors if below.~~

Never mind, clearing .svelte-kit and re-installing deps fiexed.
