### ISSUE TITLE
Make it compatible with SK version >= 1.0.0-next.359

### ISSUE THREAD

**Issue by yuanchuan** [yuanchuan/vite-plugin-autoimport#29]
There's still missing the official docs about `vite.config.js`. Will it be the single config file or both `vite.config.js` and `svelte.config.js` are required in the project?

* Document the changes to resolve #28 
* Handle `preprocessor`, maybe it's now inside `vite.config.js`.
* Update example.

**Comment by hartwm** [comment]
It's two files svelte.config.js still handles preprocessor

**Comment by yuanchuan** [comment]
Just updated the readme file
