### ISSUE TITLE
Sveltekit: missing-declaration

### ISSUE THREAD

**Issue by lordelix** [yuanchuan/vite-plugin-autoimport#3]
Removing the JS imports for components throws the `missing-declaration` error:

![Bildschirmfoto 2022-03-18 um 18 57 29](https://user-images.githubusercontent.com/12717530/159057772-e44a8672-76d4-4969-b6e0-56508e641976.png)

**This would need to be suppressed.**

Maybe add a hint on how to configure this in the `svelte.config.js` file.
(Unfortunately, I don't know how)

**Comment by yuanchuan** [comment]
Are you using VSCode? It seems the warning message comes from one of its plugins

**Comment by ohmree** [comment]
Isn't this by design? Nothing is informing the language service about the imports so it complains.

[`unplugin-vue-components`](https://github.com/antfu/unplugin-vue-components) solves this by generating a `components.d.ts` file that informs the language service about the components.

It looks like this:
```ts
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Alerts: typeof import('./components/Alerts.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default'];
    ChartExample: typeof import('./components/ChartExample.vue')['default']
    Donut: typeof import('./components/Donut.vue')['default'];
    FaSolidBolt: typeof import('~icons/fa-solid/bolt')['default']
    FaSolidCheckCircle: typeof import('~icons/fa-solid/check-circle')['default']
    FaSolidExclamationCircle: typeof import('~icons/fa-solid/exclamation-circle')['default']
    FaSolidInfoCircle: typeof import('~icons/fa-solid/info-circle')['default']
    FaSolidPlug: typeof import('~icons/fa-solid/plug')['default']
    FaSolidSlidersH: typeof import('~icons/fa-solid/sliders-h')['default']
    FaSolidTimesCircle: typeof import('~icons/fa-solid/times-circle')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogView: typeof import('./components/LogView.vue')['default']
  }
}

export { }
```

**Comment by stolinski** [comment]
@felixheidecke did you get this figured out? I'm still seeing this regardless of what I do in my d.ts file

**Comment by dummdidumm** [comment]
The d.ts file will silence errors by typescript that it cannot find the module. The mentioned warning here is from the Svelte compiler, which cannot be silenced like this. There currently isn't a way to silence a warning across svelte-check, the ide and Kit through a single setting, but they all have ways to silence this on their own (see options of the extension/svelte-check readme/vite-plugin-svelte readme)

**Comment by greendesertsnow** [comment]
This sole issue is the only reason I avoid using this library.
You won't believe how many times I've been allured into using Nuxt 3 instead, just for this feature.

**Comment by elliott-with-the-longest-name-on-github** [comment]
FYI, if you're willing to be a bit heavy-handed, you can disable this warning under the Svelte extension for VSCode:

![image](https://user-images.githubusercontent.com/76245373/170151410-0c1aec24-9b74-4ce9-9d2a-6d12d42c8179.png)

This will at least suppress the warning and let you use the editor without red squigglies. @dummdidumm linked the other places you may have to suppress it.
