### ISSUE TITLE
Remove duplicated string in component name ?

### ISSUE THREAD

**Issue by Extarys** [yuanchuan/vite-plugin-autoimport#38]
I'm starting a Svelte project with https://github.com/huntabyte/shadcn-svelte

All components are installed inside `lib/components/ui` like so:
```
./button/button.svelte
./alert/alert.svelte
./alert/alert-title.svelte
./alert/alert-description.svelte
```

Therefore, when I need to use a button, I need to use `<UiButtonButton>` and `<UiAlertAlert>`. Is there a way to make this more enjoyable ? :)

**Comment by yuanchuan** [comment]
You can use `prefix` and `flat` together

https://github.com/yuanchuan/sveltekit-autoimport?tab=readme-ov-file#prefix

https://github.com/yuanchuan/sveltekit-autoimport?tab=readme-ov-file#flat

**Comment by yuanchuan** [comment]
Was it helpful?

**Comment by Extarys** [comment]
@yuanchuan Oh, I missed your reply, I was submerged in notifications.
I'll test this out, thank you very much!
