### ISSUE TITLE
Nested Components

### ISSUE THREAD

**Issue by joshua1** [yuanchuan/vite-plugin-autoimport#5]
Hi @yuanchuan . First off, Nice one for svelte projects. I wish to know how nested components in the components folders are handled by this. Are they namespaced into the component name like unplugin-vue-components ?

**Comment by yuanchuan** [comment]
Currently the folder names are being ignored but I've planned to keep them as namespaces in next version

**Comment by yuanchuan** [comment]
Just publish v1.5.0. Now components will be namespaced by default.

https://github.com/yuanchuan/vite-plugin-autoimport/releases/tag/v1.5.0
