### ISSUE TITLE
Import Broken When lang="ts

### ISSUE THREAD

**Issue by stolinski** [yuanchuan/vite-plugin-autoimport#6]
Reproduction: https://github.com/stolinski/auto-import-lib-bug

```
1 |  <script
2 |  import FormButton from '../components/form/button.svelte'
                               ^
3 |  lang="ts">
4 |  </script>
 ```

**Comment by stolinski** [comment]
The issue is def with https://github.com/yuanchuan/vite-plugin-autoimport/blob/main/src/lib.js#L145 as it's just counting chars. I'll make a pr, with a fix that worked for me.

**Comment by stolinski** [comment]
OK, made a PR here https://github.com/yuanchuan/vite-plugin-autoimport/pull/7

**Comment by greendesertsnow** [comment]
Module importing doesn't work either.

**Comment by yuanchuan** [comment]
Thanks @stolinski,  I'll do more test later!

**Comment by yuanchuan** [comment]
> Module importing doesn't work either.

Hi @greendesertsnow, would you give a more specific example?

**Comment by greendesertsnow** [comment]
I wasn't able to 
import {onUpdate} from 'svelte' 
automatically using the plugin if the 
<script lang=ts>
so when I change the lang=js, the plugin functions properly.

**Comment by yuanchuan** [comment]
> I wasn't able to import {onUpdate} from 'svelte' automatically using the plugin if the
> 
> <script lang=ts> so when I change the lang=js, the plugin functions properly.

@greendesertsnow Hi, I can't reproduce it. Please try version `1.6.2`. 

By the way, the `onUpdate` function does not exist.

**Comment by greendesertsnow** [comment]
Whoops wrong name. I apologize for that. It's working now.
I get a crbug/1173575, non-JS module files deprecated error
When I add ```autoImport( { module:{ '$app/store: [ 'page' ] } } )```
Shall I open a new issue for that?
I know it's not a commonly used module but just asking because I want know if adding all modules from the start brings about any performance issues?

**Comment by yuanchuan** [comment]
> Whoops wrong name. I apologize for that. It's working now. I get a crbug/1173575, non-JS module files deprecated error When I add `autoImport( { module:{ '$app/store: [ 'page' ] } } )` Shall I open a new issue for that? I know it's not a commonly used module but just asking because I want know if adding all modules from the start brings about any performance issues?

Yes please! I'll see if I can fix that
