### ISSUE TITLE
Importing '$app/stores' : ['page'] brings about crbug

### ISSUE THREAD

**Issue by greendesertsnow** [yuanchuan/vite-plugin-autoimport#9]
Hey,
The 'page' module out of all other $app/stores modules causes this error.
![image](https://user-images.githubusercontent.com/88274580/164408581-ea7f5200-6291-4701-880a-d7d88c26b0fa.png)
VM10:6772 crbug/1173575, non-JS module files deprecated.

```
autoImport({
    	module: {
    	    '$app/stores': [

			'page',
		
		]
	}
})
```
The other  'getStores','navigating' ,'session','updated', imports are working just fine as of 1.6.2

Thank you for your time and effort. 
Great library, I hope it becomes a default part of the main Sveltekit one day, like its port library is for Nuxt 3 now.

**Comment by yuanchuan** [comment]
Current workaround: Limit the lookup to prevent it from processing `.sveltekit` folder.

```js
autoImport({
  include: ['./src/**/*.svelte'], 
  /* ... */
})
```
